spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # PAYMENT SERVICE
            - id: payment-service
              uri: http://localhost:9091
              predicates:
                - Path=/payment-service/**
              filters:
                - StripPrefix=1

            # USER SERVICE
            - id: user-service
              uri: http://localhost:9093
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1

            # PRODUCT SERVICE
            - id: product-service
              uri: http://localhost:9092
              predicates:
                - Path=/product-service/**
              filters:
                - StripPrefix=1

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: Payment Service
        url: /payment-service/v3/api-docs

      - name: User Service
        url: /user-service/v3/api-docs

      - name: Product Service
        url: /product-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
